backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: 'dist/uploads/images' #Live image Uploads
public_folder: '/_uploads/images' #prebuild image Uploads

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

collections:
  # Our article posts
  - name: 'article' # Used in routes, e.g., /admin/collections/article
    label: 'Post' # Used in the UI
    folder: 'src/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'pages/post.njk',
        } #Layout option
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'string',
          default: 'Anonymous',
        }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  # Our pages e.g. About
  # - name: "pages"
  #   label: "Page"
  #   folder: "pages"
  #   create: false
  #   slug: "{{slug}}"
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Publish Date", name: "date", widget: "datetime" }
  #     - { label: "Permalink", name: "permalink", widget: "string" }
  #     - label: "Navigation"
  #       name: "eleventyNavigation"
  #       widget: "object"
  #       fields:
  #         - { label: "Key", name: "key", widget: "string" }
  #         - { label: "Order", name: "order", widget: "number", default: 0 }
  #     - { label: "Body", name: "body", widget: "markdown" }
