backend:
  name: git-gateway
  branch: master
  publish_mode: editorial_workflow
media_folder: 'dist/img/uploads'
#public_folder: '/uploads/images' #prebuild image Uploads
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
collections:
  - name: 'post'
    label: 'Posts'
    folder: 'src/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'pages/post.njk',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Hero Image', name: 'heroImage', widget: 'image' }
      - { label: 'Date', name: 'date', widget: 'date', default: '' }
      - { label: 'Post Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }
      - {
          label: 'Article Type',
          name: 'articleType',
          widget: 'select',
          options:
            [
              '3dprinting',
              'designsystem',
              'homeautomation',
              'photography',
              'portfolio',
              'tips',
              'ux',
            ],
        }
      - {
          label: 'Showcase',
          name: 'showcase',
          widget: 'boolean',
          default: false,
        }
