backend:
  name: git-gateway
  branch: master # Branch to update
media_folder: 'dist/uploads/images' #Live image Uploads
public_folder: '/uploads/images' #prebuild image Uploads
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
collections:
  - name: 'post' #Collection name that matches the .json tags
    label: 'Posts' #CMS collection name
    folder: 'src/posts' #Folder where posts live
    create: true #Can a new posts be created
    slug: '{{year}}-{{month}}-{{day}}-{{pageTitle}}' #this sets the URL for the post
    fields: #What fields are displayed to edit the post
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'pages/post.njk',
        } #Layout option
      - { label: 'Title', name: 'pageTitle', widget: 'string' }
      - { label: 'Description', name: 'pageDescription', widget: 'string' }
      - { label: 'Hero Image', name: 'heroImage', widget: 'image' }
      - { label: 'Date', name: 'date', widget: 'date', default: '' }
      - { label: 'Post Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Article Type',
          name: 'articleType',
          widget: 'select',
          options:
            [
              '3dprinting',
              'designsystem',
              'homeautomation',
              'photography',
              'portfolio',
              'tips',
              'ux',
            ],
        } #Adds Article type tag
      - {
          label: 'Showcase',
          name: 'showcase',
          widget: 'boolean',
          default: false,
        } #Set Article to Showcase
