backend:
  name: git-gateway
  branch: master # Branch to update
  publish_mode: editorial_workflow
media_folder: 'dist/img/uploads' #Live image Uploads
#public_folder: '/uploads/images' #prebuild image Uploads
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
collections:
  - name: 'post' #Collection name that matches the .json tags
    label: 'Posts' #CMS collection name
    folder: 'src/posts' #Folder where posts live
    create: true #Can a new posts be created
    slug: '{{year}}-{{month}}-{{day}}-{{pageTitle}}' #this sets the URL for the post
